(function(b,d){function a(g,d){var a,f;a=g.nodeName.toLowerCase();if("area"===a){a=g.parentNode;f=a.name;if(!g.href||!f||"map"!==a.nodeName.toLowerCase())return!1;a=b("img[usemap=#"+f+"]")[0];return!!a&&c(a)}return(/input|select|textarea|button|object/.test(a)?!g.disabled:"a"===a?g.href||d:d)&&c(g)}function c(g){return!b(g).parents().andSelf().filter(function(){return"hidden"===b.css(this,"visibility")||b.expr.filters.hidden(this)}).length}var e=0,f=/^ui-id-\d+$/;b.ui=b.ui||{};b.ui.version||(b.extend(b.ui,
{version:"@VERSION",keyCode:{BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38}}),b.fn.extend({_focus:b.fn.focus,focus:function(g,d){return"number"===typeof g?this.each(function(){var a=this;setTimeout(function(){b(a).focus();d&&d.call(a)},g)}):this._focus.apply(this,arguments)},scrollParent:function(){var g;
g=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.css(this,"position"))&&/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0);return/fixed/.test(this.css("position"))||!g.length?b(document):
g},zIndex:function(g){if(g!==d)return this.css("zIndex",g);if(this.length)for(var g=b(this[0]),a;g.length&&g[0]!==document;){a=g.css("position");if("absolute"===a||"relative"===a||"fixed"===a)if(a=parseInt(g.css("zIndex"),10),!isNaN(a)&&0!==a)return a;g=g.parent()}return 0},uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++e)})},removeUniqueId:function(){return this.each(function(){f.test(this.id)&&b(this).removeAttr("id")})}}),b("<a>").outerWidth(1).jquery||b.each(["Width",
"Height"],function(a,c){function f(a,d,g,c){b.each(l,function(){d-=parseFloat(b.css(a,"padding"+this))||0;g&&(d-=parseFloat(b.css(a,"border"+this+"Width"))||0);c&&(d-=parseFloat(b.css(a,"margin"+this))||0)});return d}var l="Width"===c?["Left","Right"]:["Top","Bottom"],h=c.toLowerCase(),e={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+c]=function(a){return a===d?e["inner"+c].call(this):this.each(function(){b(this).css(h,
f(this,a)+"px")})};b.fn["outer"+c]=function(a,d){return"number"!==typeof a?e["outer"+c].call(this,a):this.each(function(){b(this).css(h,f(this,a,!0,d)+"px")})}}),b.extend(b.expr[":"],{data:b.expr.createPseudo?b.expr.createPseudo(function(a){return function(d){return!!b.data(d,a)}}):function(a,d,c){return!!b.data(a,c[3])},focusable:function(d){return a(d,!isNaN(b.attr(d,"tabindex")))},tabbable:function(d){var c=b.attr(d,"tabindex"),f=isNaN(c);return(f||0<=c)&&a(d,!f)}}),b(function(){var a=document.body,
d=a.appendChild(d=document.createElement("div"));d.offsetHeight;b.extend(d.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});b.support.minHeight=100===d.offsetHeight;b.support.selectstart="onselectstart"in d;a.removeChild(d).style.display="none"}),b.fn.extend({disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(b){b.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}}),
b.extend(b.ui,{plugin:{add:function(a,d,c){var f,a=b.ui[a].prototype;for(f in c)a.plugins[f]=a.plugins[f]||[],a.plugins[f].push([d,c[f]])},call:function(b,a,d){var c=b.plugins[a];if(c&&b.element[0].parentNode&&11!==b.element[0].parentNode.nodeType)for(a=0;a<c.length;a++)b.options[c[a][0]]&&c[a][1].apply(b.element,d)}},contains:b.contains,hasScroll:function(a,d){if("hidden"===b(a).css("overflow"))return!1;var c=d&&"left"===d?"scrollLeft":"scrollTop",f=!1;if(0<a[c])return!0;a[c]=1;f=0<a[c];a[c]=0;return f},
isOverAxis:function(b,a,d){return b>a&&b<a+d},isOver:function(a,d,c,f,e,j){return b.ui.isOverAxis(a,c,e)&&b.ui.isOverAxis(d,f,j)}}))})(mQuery);
(function(b,d){var a=0,c=Array.prototype.slice,e=b.cleanData;b.cleanData=function(a){for(var d=0,c;null!=(c=a[d]);d++)try{b(c).triggerHandler("remove")}catch(i){}e(a)};b.widget=function(a,d,c){var i,e,h,j,m=a.split(".")[0],a=a.split(".")[1];i=m+"-"+a;c||(c=d,d=b.Widget);b.expr[":"][i.toLowerCase()]=function(a){return!!b.data(a,i)};b[m]=b[m]||{};e=b[m][a];h=b[m][a]=function(b,a){if(!this._createWidget)return new h(b,a);arguments.length&&this._createWidget(b,a)};b.extend(h,e,{version:c.version,_proto:b.extend({},
c),_childConstructors:[]});j=new d;j.options=b.widget.extend({},j.options);b.each(c,function(a,f){if(b.isFunction(f)){var i=function(){return d.prototype[a].apply(this,arguments)},e=function(b){return d.prototype[a].apply(this,b)};c[a]=function(){var b=this._super,a=this._superApply,d;this._super=i;this._superApply=e;d=f.apply(this,arguments);this._super=b;this._superApply=a;return d}}});h.prototype=b.widget.extend(j,{widgetEventPrefix:a},c,{constructor:h,namespace:m,widgetName:a,widgetBaseClass:i,
widgetFullName:i});e?(b.each(e._childConstructors,function(a,d){var c=d.prototype;b.widget(c.namespace+"."+c.widgetName,h,d._proto)}),delete e._childConstructors):d._childConstructors.push(h);b.widget.bridge(a,h)};b.widget.extend=function(a){for(var g=c.call(arguments,1),k=0,i=g.length,e,h;k<i;k++)for(e in g[k])h=g[k][e],g[k].hasOwnProperty(e)&&h!==d&&(a[e]=b.isPlainObject(h)?b.widget.extend({},a[e],h):h);return a};b.widget.bridge=function(a,g){var e=g.prototype.widgetFullName;b.fn[a]=function(i){var l=
"string"===typeof i,h=c.call(arguments,1),j=this,i=!l&&h.length?b.widget.extend.apply(null,[i].concat(h)):i;l?this.each(function(){var c,g=b.data(this,e);if(!g)return b.error("cannot call methods on "+a+" prior to initialization; attempted to call method '"+i+"'");if(!b.isFunction(g[i])||"_"===i.charAt(0))return b.error("no such method '"+i+"' for "+a+" widget instance");c=g[i].apply(g,h);if(c!==g&&c!==d)return j=c&&c.jquery?j.pushStack(c.get()):c,!1}):this.each(function(){var a=b.data(this,e);a?
a.option(i||{})._init():new g(i,this)});return j}};b.Widget=function(){};b.Widget._childConstructors=[];b.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{disabled:!1,create:null},_createWidget:function(d,c){c=b(c||this.defaultElement||this)[0];this.element=b(c);this.uuid=a++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=b.widget.extend({},this.options,this._getCreateOptions(),d);this.bindings=b();this.hoverable=b();this.focusable=b();c!==
this&&(b.data(c,this.widgetName,this),b.data(c,this.widgetFullName,this),this._on({remove:"destroy"}),this.document=b(c.style?c.ownerDocument:c.document||c),this.window=b(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:b.noop,_getCreateEventData:b.noop,_create:b.noop,_init:b.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(b.camelCase(this.widgetFullName));
this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:b.noop,widget:function(){return this.element},option:function(a,c){var e=a,i,l,h;if(0===arguments.length)return b.widget.extend({},this.options);if("string"===typeof a)if(e={},i=a.split("."),a=i.shift(),i.length){l=e[a]=b.widget.extend({},
this.options[a]);for(h=0;h<i.length-1;h++)l[i[h]]=l[i[h]]||{},l=l[i[h]];a=i.pop();if(c===d)return l[a]===d?null:l[a];l[a]=c}else{if(c===d)return this.options[a]===d?null:this.options[a];e[a]=c}this._setOptions(e);return this},_setOptions:function(b){for(var a in b)this._setOption(a,b[a]);return this},_setOption:function(b,a){this.options[b]=a;"disabled"===b&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!a).attr("aria-disabled",a),this.hoverable.removeClass("ui-state-hover"),
this.focusable.removeClass("ui-state-focus"));return this},enable:function(){return this._setOption("disabled",!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(a,c){c?(a=b(a),this.bindings=this.bindings.add(a)):(c=a,a=this.element);var d=this;b.each(c,function(c,g){function e(){if(!(!0===d.options.disabled||b(this).hasClass("ui-state-disabled")))return("string"===typeof g?d[g]:g).apply(d,arguments)}"string"!==typeof g&&(e.guid=g.guid=g.guid||e.guid||b.guid++);var j=c.match(/^(\w+)\s*(.*)$/),
m=j[1]+d.eventNamespace;(j=j[2])?d.widget().delegate(j,m,e):a.bind(m,e)})},_off:function(b,a){a=(a||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;b.unbind(a).undelegate(a)},_delay:function(b,a){var c=this;return setTimeout(function(){return("string"===typeof b?c[b]:b).apply(c,arguments)},a||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){b(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){b(a.currentTarget).removeClass("ui-state-hover")}})},
_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){b(a.currentTarget).addClass("ui-state-focus")},focusout:function(a){b(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(a,c,d){var e,l=this.options[a],d=d||{},c=b.Event(c);c.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase();c.target=this.element[0];if(a=c.originalEvent)for(e in a)e in c||(c[e]=a[e]);this.element.trigger(c,d);return!(b.isFunction(l)&&!1===l.apply(this.element[0],
[c].concat(d))||c.isDefaultPrevented())}};b.each({show:"fadeIn",hide:"fadeOut"},function(a,c){b.Widget.prototype["_"+a]=function(d,e,l){"string"===typeof e&&(e={effect:e});var h,j=!e?a:!0===e||"number"===typeof e?c:e.effect||c,e=e||{};"number"===typeof e&&(e={duration:e});h=!b.isEmptyObject(e);e.complete=l;e.delay&&d.delay(e.delay);if(h&&b.effects&&(b.effects.effect[j]||!1!==b.uiBackCompat&&b.effects[j]))d[a](e);else if(j!==a&&d[j])d[j](e.duration,e.easing,l);else d.queue(function(c){b(this)[a]();
l&&l.call(d[0]);c()})}});!1!==b.uiBackCompat&&(b.Widget.prototype._getCreateOptions=function(){return b.metadata&&b.metadata.get(this.element[0])[this.widgetName]})})(mQuery);
(function(b){var d=!1;b(document).mouseup(function(){d=!1});b.widget("ui.mouse",{version:"@VERSION",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0},_mouseInit:function(){var a=this;this.element.bind("mousedown."+this.widgetName,function(b){return a._mouseDown(b)}).bind("click."+this.widgetName,function(c){if(!0===b.data(c.target,a.widgetName+".preventClickEvent"))return b.removeData(c.target,a.widgetName+".preventClickEvent"),c.stopImmediatePropagation(),!1});this.started=
!1},_mouseDestroy:function(){this.element.unbind("."+this.widgetName);this._mouseMoveDelegate&&b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate)},_mouseDown:function(a){if(!d){this._mouseStarted&&this._mouseUp(a);this._mouseDownEvent=a;var c=this,e=1===a.which,f="string"===typeof this.options.cancel&&a.target.nodeName?b(a.target).closest(this.options.cancel).length:!1;if(!e||f||!this._mouseCapture(a))return!0;this.mouseDelayMet=
!this.options.delay;this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){c.mouseDelayMet=!0},this.options.delay));if(this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(a),!this._mouseStarted))return a.preventDefault(),!0;!0===b.data(a.target,this.widgetName+".preventClickEvent")&&b.removeData(a.target,this.widgetName+".preventClickEvent");this._mouseMoveDelegate=function(b){return c._mouseMove(b)};this._mouseUpDelegate=function(b){return c._mouseUp(b)};
b(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);a.preventDefault();return d=!0}},_mouseMove:function(a){if(b.browser.msie&&!(9<=document.documentMode)&&!a.button)return this._mouseUp(a);if(this._mouseStarted)return this._mouseDrag(a),a.preventDefault();this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&((this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,a))?this._mouseDrag(a):this._mouseUp(a));return!this._mouseStarted},
_mouseUp:function(a){b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,a.target===this._mouseDownEvent.target&&b.data(a.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(a));return!1},_mouseDistanceMet:function(b){return Math.max(Math.abs(this._mouseDownEvent.pageX-b.pageX),Math.abs(this._mouseDownEvent.pageY-b.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},
_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}})})(mQuery);
(function(b,d){function a(b,a,c){return[parseInt(b[0],10)*(j.test(b[0])?a/100:1),parseInt(b[1],10)*(j.test(b[1])?c/100:1)]}b.ui=b.ui||{};var c,e=Math.max,f=Math.abs,g=Math.round,k=/left|center|right/,i=/top|center|bottom/,l=/[\+\-]\d+%?/,h=/^\w+/,j=/%$/,m=b.fn.position;b.position={scrollbarWidth:function(){if(c!==d)return c;var a,e,f=b("<div style='display:block;width:50px;height:50px;overflow:hidden;'><div style='height:100px;width:auto;'></div></div>");e=f.children()[0];b("body").append(f);a=e.offsetWidth;
f.css("overflow","scroll");e=e.offsetWidth;a===e&&(e=f[0].clientWidth);f.remove();return c=a-e},getScrollInfo:function(a){var c=a.isWindow?"":a.element.css("overflow-x"),d=a.isWindow?"":a.element.css("overflow-y"),d="scroll"===d||"auto"===d&&a.height<a.element[0].scrollHeight;return{width:"scroll"===c||"auto"===c&&a.width<a.element[0].scrollWidth?b.position.scrollbarWidth():0,height:d?b.position.scrollbarWidth():0}},getWithinInfo:function(a){var a=b(a||window),c=b.isWindow(a[0]);return{element:a,
isWindow:c,offset:a.offset()||{left:0,top:0},scrollLeft:a.scrollLeft(),scrollTop:a.scrollTop(),width:c?a.width():a.outerWidth(),height:c?a.height():a.outerHeight()}}};b.fn.position=function(c){if(!c||!c.of)return m.apply(this,arguments);var c=b.extend({},c),d,w,x,j,t,y=b(c.of),p=b.position.getWithinInfo(c.within),r=b.position.getScrollInfo(p),z=y[0],q=(c.collision||"flip").split(" "),s={};9===z.nodeType?(w=y.width(),x=y.height(),j={top:0,left:0}):b.isWindow(z)?(w=y.width(),x=y.height(),j={top:y.scrollTop(),
left:y.scrollLeft()}):z.preventDefault?(c.at="left top",w=x=0,j={top:z.pageY,left:z.pageX}):(w=y.outerWidth(),x=y.outerHeight(),j=y.offset());t=b.extend({},j);b.each(["my","at"],function(){var a=(c[this]||"").split(" "),b,d;1===a.length&&(a=k.test(a[0])?a.concat(["center"]):i.test(a[0])?["center"].concat(a):["center","center"]);a[0]=k.test(a[0])?a[0]:"center";a[1]=i.test(a[1])?a[1]:"center";b=l.exec(a[0]);d=l.exec(a[1]);s[this]=[b?b[0]:0,d?d[0]:0];c[this]=[h.exec(a[0])[0],h.exec(a[1])[0]]});1===q.length&&
(q[1]=q[0]);"right"===c.at[0]?t.left+=w:"center"===c.at[0]&&(t.left+=w/2);"bottom"===c.at[1]?t.top+=x:"center"===c.at[1]&&(t.top+=x/2);d=a(s.at,w,x);t.left+=d[0];t.top+=d[1];return this.each(function(){var h,i,k=b(this),l=k.outerWidth(),m=k.outerHeight(),z=parseInt(b.css(this,"marginLeft"),10)||0,u=parseInt(b.css(this,"marginTop"),10)||0,v=l+z+(parseInt(b.css(this,"marginRight"),10)||0)+r.width,A=m+u+(parseInt(b.css(this,"marginBottom"),10)||0)+r.height,n=b.extend({},t),B=a(s.my,k.outerWidth(),k.outerHeight());
"right"===c.my[0]?n.left-=l:"center"===c.my[0]&&(n.left-=l/2);"bottom"===c.my[1]?n.top-=m:"center"===c.my[1]&&(n.top-=m/2);n.left+=B[0];n.top+=B[1];b.support.offsetFractions||(n.left=g(n.left),n.top=g(n.top));h={marginLeft:z,marginTop:u};b.each(["left","top"],function(a,e){if(b.ui.position[q[a]])b.ui.position[q[a]][e](n,{targetWidth:w,targetHeight:x,elemWidth:l,elemHeight:m,collisionPosition:h,collisionWidth:v,collisionHeight:A,offset:[d[0]+B[0],d[1]+B[1]],my:c.my,at:c.at,within:p,elem:k})});b.fn.bgiframe&&
k.bgiframe();c.using&&(i=function(a){var b=j.left-n.left,d=b+w-l,g=j.top-n.top,C=g+x-m,h={target:{element:y,left:j.left,top:j.top,width:w,height:x},element:{element:k,left:n.left,top:n.top,width:l,height:m},horizontal:0>d?"left":0<b?"right":"center",vertical:0>C?"top":0<g?"bottom":"middle"};w<l&&f(b+d)<w&&(h.horizontal="center");x<m&&f(g+C)<x&&(h.vertical="middle");h.important=e(f(b),f(d))>e(f(g),f(C))?"horizontal":"vertical";c.using.call(this,a,h)});k.offset(b.extend(n,{using:i}))})};b.ui.position=
{fit:{left:function(a,b){var c=b.within,d=c.isWindow?c.scrollLeft:c.offset.left,f=c.width,g=a.left-b.collisionPosition.marginLeft,c=d-g,h=g+b.collisionWidth-f-d;b.collisionWidth>f?0<c&&0>=h?(d=a.left+c+b.collisionWidth-f-d,a.left+=c-d):a.left=0<h&&0>=c?d:c>h?d+f-b.collisionWidth:d:a.left=0<c?a.left+c:0<h?a.left-h:e(a.left-g,a.left)},top:function(a,b){var c=b.within,d=c.isWindow?c.scrollTop:c.offset.top,f=b.within.height,g=a.top-b.collisionPosition.marginTop,c=d-g,h=g+b.collisionHeight-f-d;b.collisionHeight>
f?0<c&&0>=h?(d=a.top+c+b.collisionHeight-f-d,a.top+=c-d):a.top=0<h&&0>=c?d:c>h?d+f-b.collisionHeight:d:a.top=0<c?a.top+c:0<h?a.top-h:e(a.top-g,a.top)}},flip:{left:function(a,b){var c=b.within,d=c.offset.left+c.scrollLeft,e=c.width,g=c.isWindow?c.scrollLeft:c.offset.left,h=a.left-b.collisionPosition.marginLeft,c=h-g,k=h+b.collisionWidth-e-g,h="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,i="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,j=-2*b.offset[0];if(0>c){if(d=
a.left+h+i+j+b.collisionWidth-e-d,0>d||d<f(c))a.left+=h+i+j}else if(0<k&&(d=a.left-b.collisionPosition.marginLeft+h+i+j-g,0<d||f(d)<k))a.left+=h+i+j},top:function(a,b){var c=b.within,d=c.offset.top+c.scrollTop,e=c.height,g=c.isWindow?c.scrollTop:c.offset.top,h=a.top-b.collisionPosition.marginTop,c=h-g,k=h+b.collisionHeight-e-g,h="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,i="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,j=-2*b.offset[1];if(0>c){if(d=a.top+
h+i+j+b.collisionHeight-e-d,a.top+h+i+j>c&&(0>d||d<f(c)))a.top+=h+i+j}else if(0<k&&(d=a.top-b.collisionPosition.marginTop+h+i+j-g,a.top+h+i+j>k&&(0<d||f(d)<k)))a.top+=h+i+j}},flipfit:{left:function(){b.ui.position.flip.left.apply(this,arguments);b.ui.position.fit.left.apply(this,arguments)},top:function(){b.ui.position.flip.top.apply(this,arguments);b.ui.position.fit.top.apply(this,arguments)}}};var r,p,q,u,s=document.getElementsByTagName("body")[0];q=document.createElement("div");r=document.createElement(s?
"div":"body");p={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};s&&b.extend(p,{position:"absolute",left:"-1000px",top:"-1000px"});for(u in p)r.style[u]=p[u];r.appendChild(q);p=s||document.documentElement;p.insertBefore(r,p.firstChild);q.style.cssText="position: absolute; left: 10.7432222px;";q=b(q).offset().left;b.support.offsetFractions=10<q&&11>q;r.innerHTML="";p.removeChild(r);if(!1!==b.uiBackCompat){var v=mQuery,A=v.fn.position;v.fn.position=function(a){if(!a||!a.offset)return A.call(this,
a);var b=a.offset.split(" "),c=a.at.split(" ");1===b.length&&(b[1]=b[0]);/^\d/.test(b[0])&&(b[0]="+"+b[0]);/^\d/.test(b[1])&&(b[1]="+"+b[1]);1===c.length&&(/left|center|right/.test(c[0])?c[1]="center":(c[1]=c[0],c[0]="center"));return A.call(this,v.extend(a,{at:c[0]+b[0]+" "+c[1]+b[1],offset:d}))}}})(mQuery);
jQuery(function(b){b.widget("ui.draggable",b.ui.mouse,{version:"@VERSION",widgetEventPrefix:"drag",options:{addClasses:!0,appendTo:"parent",axis:!1,connectToSortable:!1,containment:!1,cursor:"auto",cursorAt:!1,grid:!1,handle:!1,helper:"original",iframeFix:!1,opacity:!1,refreshPositions:!1,revert:!1,revertDuration:500,scope:"default",scroll:!0,scrollSensitivity:20,scrollSpeed:20,snap:!1,snapMode:"both",snapTolerance:20,stack:!1,zIndex:!1},_create:function(){"original"==this.options.helper&&!/^(?:r|a|f)/.test(this.element.css("position"))&&
(this.element[0].style.position="relative");this.options.addClasses&&this.element.addClass("ui-draggable");this.options.disabled&&this.element.addClass("ui-draggable-disabled");this._mouseInit()},_destroy:function(){this.element.removeClass("ui-draggable ui-draggable-dragging ui-draggable-disabled");this._mouseDestroy()},_mouseCapture:function(d){var a=this.options;if(this.helper||a.disabled||b(d.target).is(".ui-resizable-handle"))return!1;this.handle=this._getHandle(d);if(!this.handle)return!1;b(!0===
a.iframeFix?"iframe":a.iframeFix).each(function(){b('<div class="ui-draggable-iframeFix" style="background: #fff;"></div>').css({width:this.offsetWidth+"px",height:this.offsetHeight+"px",position:"absolute",opacity:"0.001",zIndex:1E3}).css(b(this).offset()).appendTo("body")});return!0},_mouseStart:function(d){var a=this.options;this.helper=this._createHelper(d);this.helper.addClass("ui-draggable-dragging");this._cacheHelperProportions();b.ui.ddmanager&&(b.ui.ddmanager.current=this);this._cacheMargins();
this.cssPosition=this.helper.css("position");this.scrollParent=this.helper.scrollParent();this.offset=this.positionAbs=this.element.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};b.extend(this.offset,{click:{left:d.pageX-this.offset.left,top:d.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this.position=this._generatePosition(d);this.originalPageX=d.pageX;this.originalPageY=d.pageY;
a.cursorAt&&this._adjustOffsetFromHelper(a.cursorAt);a.containment&&this._setContainment();if(!1===this._trigger("start",d))return this._clear(),!1;this._cacheHelperProportions();b.ui.ddmanager&&!a.dropBehaviour&&b.ui.ddmanager.prepareOffsets(this,d);this._mouseDrag(d,!0);b.ui.ddmanager&&b.ui.ddmanager.dragStart(this,d);return!0},_mouseDrag:function(d,a){this.position=this._generatePosition(d);this.positionAbs=this._convertPositionTo("absolute");if(!a){var c=this._uiHash();if(!1===this._trigger("drag",
d,c))return this._mouseUp({}),!1;this.position=c.position}if(!this.options.axis||"y"!=this.options.axis)this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||"x"!=this.options.axis)this.helper[0].style.top=this.position.top+"px";b.ui.ddmanager&&b.ui.ddmanager.drag(this,d);return!1},_mouseStop:function(d){var a=!1;b.ui.ddmanager&&!this.options.dropBehaviour&&(a=b.ui.ddmanager.drop(this,d));this.dropped&&(a=this.dropped,this.dropped=!1);for(var c=this.element[0],e=!1;c&&(c=c.parentNode);)c==
document&&(e=!0);if(!e&&"original"===this.options.helper)return!1;if("invalid"==this.options.revert&&!a||"valid"==this.options.revert&&a||!0===this.options.revert||b.isFunction(this.options.revert)&&this.options.revert.call(this.element,a)){var f=this;b(this.helper).animate(this.originalPosition,parseInt(this.options.revertDuration,10),function(){!1!==f._trigger("stop",d)&&f._clear()})}else!1!==this._trigger("stop",d)&&this._clear();return!1},_mouseUp:function(d){b("div.ui-draggable-iframeFix").each(function(){this.parentNode.removeChild(this)});
b.ui.ddmanager&&b.ui.ddmanager.dragStop(this,d);return b.ui.mouse.prototype._mouseUp.call(this,d)},cancel:function(){this.helper.is(".ui-draggable-dragging")?this._mouseUp({}):this._clear();return this},_getHandle:function(d){var a=!this.options.handle||!b(this.options.handle,this.element).length?!0:!1;b(this.options.handle,this.element).find("*").andSelf().each(function(){this==d.target&&(a=!0)});return a},_createHelper:function(d){var a=this.options,d=b.isFunction(a.helper)?b(a.helper.apply(this.element[0],
[d])):"clone"==a.helper?this.element.clone().removeAttr("id"):this.element;d.parents("body").length||d.appendTo("parent"==a.appendTo?this.element[0].parentNode:a.appendTo);d[0]!=this.element[0]&&!/(fixed|absolute)/.test(d.css("position"))&&d.css("position","absolute");return d},_adjustOffsetFromHelper:function(d){"string"==typeof d&&(d=d.split(" "));b.isArray(d)&&(d={left:+d[0],top:+d[1]||0});"left"in d&&(this.offset.click.left=d.left+this.margins.left);"right"in d&&(this.offset.click.left=this.helperProportions.width-
d.right+this.margins.left);"top"in d&&(this.offset.click.top=d.top+this.margins.top);"bottom"in d&&(this.offset.click.top=this.helperProportions.height-d.bottom+this.margins.top)},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var d=this.offsetParent.offset();"absolute"==this.cssPosition&&(this.scrollParent[0]!=document&&b.contains(this.scrollParent[0],this.offsetParent[0]))&&(d.left+=this.scrollParent.scrollLeft(),d.top+=this.scrollParent.scrollTop());if(this.offsetParent[0]==
document.body||this.offsetParent[0].tagName&&"html"==this.offsetParent[0].tagName.toLowerCase()&&b.browser.msie)d={top:0,left:0};return{top:d.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:d.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if("relative"==this.cssPosition){var b=this.element.position();return{top:b.top-(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:b.left-(parseInt(this.helper.css("left"),
10)||0)+this.scrollParent.scrollLeft()}}return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.element.css("marginLeft"),10)||0,top:parseInt(this.element.css("marginTop"),10)||0,right:parseInt(this.element.css("marginRight"),10)||0,bottom:parseInt(this.element.css("marginBottom"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var d=this.options;"parent"==d.containment&&
(d.containment=this.helper[0].parentNode);if("document"==d.containment||"window"==d.containment)this.containment=["document"==d.containment?0:b(window).scrollLeft()-this.offset.relative.left-this.offset.parent.left,"document"==d.containment?0:b(window).scrollTop()-this.offset.relative.top-this.offset.parent.top,("document"==d.containment?0:b(window).scrollLeft())+b("document"==d.containment?document:window).width()-this.helperProportions.width-this.margins.left,("document"==d.containment?0:b(window).scrollTop())+
(b("document"==d.containment?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(d.containment)&&d.containment.constructor!=Array){var d=b(d.containment),a=d[0];if(a){d.offset();var c="hidden"!=b(a).css("overflow");this.containment=[(parseInt(b(a).css("borderLeftWidth"),10)||0)+(parseInt(b(a).css("paddingLeft"),10)||0),(parseInt(b(a).css("borderTopWidth"),10)||0)+(parseInt(b(a).css("paddingTop"),10)||
0),(c?Math.max(a.scrollWidth,a.offsetWidth):a.offsetWidth)-(parseInt(b(a).css("borderLeftWidth"),10)||0)-(parseInt(b(a).css("paddingRight"),10)||0)-this.helperProportions.width-this.margins.left-this.margins.right,(c?Math.max(a.scrollHeight,a.offsetHeight):a.offsetHeight)-(parseInt(b(a).css("borderTopWidth"),10)||0)-(parseInt(b(a).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top-this.margins.bottom];this.relative_container=d}}else d.containment.constructor==Array&&(this.containment=
d.containment)},_convertPositionTo:function(d,a){a||(a=this.position);var c="absolute"==d?1:-1,e="absolute"==this.cssPosition&&!(this.scrollParent[0]!=document&&b.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,f=/(html|body)/i.test(e[0].tagName);return{top:a.top+this.offset.relative.top*c+this.offset.parent.top*c-("fixed"==this.cssPosition?-this.scrollParent.scrollTop():f?0:e.scrollTop())*c,left:a.left+this.offset.relative.left*c+this.offset.parent.left*c-
("fixed"==this.cssPosition?-this.scrollParent.scrollLeft():f?0:e.scrollLeft())*c}},_generatePosition:function(d){var a=this.options,c="absolute"==this.cssPosition&&!(this.scrollParent[0]!=document&&b.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,e=/(html|body)/i.test(c[0].tagName),f=d.pageX,g=d.pageY;if(this.originalPosition){var k;this.containment&&(this.relative_container?(k=this.relative_container.offset(),k=[this.containment[0]+k.left,this.containment[1]+
k.top,this.containment[2]+k.left,this.containment[3]+k.top]):k=this.containment,d.pageX-this.offset.click.left<k[0]&&(f=k[0]+this.offset.click.left),d.pageY-this.offset.click.top<k[1]&&(g=k[1]+this.offset.click.top),d.pageX-this.offset.click.left>k[2]&&(f=k[2]+this.offset.click.left),d.pageY-this.offset.click.top>k[3]&&(g=k[3]+this.offset.click.top));a.grid&&(g=a.grid[1]?this.originalPageY+Math.round((g-this.originalPageY)/a.grid[1])*a.grid[1]:this.originalPageY,g=k?!(g-this.offset.click.top<k[1]||
g-this.offset.click.top>k[3])?g:!(g-this.offset.click.top<k[1])?g-a.grid[1]:g+a.grid[1]:g,f=a.grid[0]?this.originalPageX+Math.round((f-this.originalPageX)/a.grid[0])*a.grid[0]:this.originalPageX,f=k?!(f-this.offset.click.left<k[0]||f-this.offset.click.left>k[2])?f:!(f-this.offset.click.left<k[0])?f-a.grid[0]:f+a.grid[0]:f)}return{top:g-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+("fixed"==this.cssPosition?-this.scrollParent.scrollTop():e?0:c.scrollTop()),left:f-this.offset.click.left-
this.offset.relative.left-this.offset.parent.left+("fixed"==this.cssPosition?-this.scrollParent.scrollLeft():e?0:c.scrollLeft())}},_clear:function(){this.helper.removeClass("ui-draggable-dragging");this.helper[0]!=this.element[0]&&!this.cancelHelperRemoval&&this.helper.remove();this.helper=null;this.cancelHelperRemoval=!1},_trigger:function(d,a,c){c=c||this._uiHash();b.ui.plugin.call(this,d,[a,c]);"drag"==d&&(this.positionAbs=this._convertPositionTo("absolute"));return b.Widget.prototype._trigger.call(this,
d,a,c)},plugins:{},_uiHash:function(){return{helper:this.helper,position:this.position,originalPosition:this.originalPosition,offset:this.positionAbs}}});b.ui.plugin.add("draggable","connectToSortable",{start:function(d,a){var c=b(this).data("draggable"),e=c.options,f=b.extend({},a,{item:c.element});c.sortables=[];b(e.connectToSortable).each(function(){var a=b.data(this,"sortable");a&&!a.options.disabled&&(c.sortables.push({instance:a,shouldRevert:a.options.revert}),a.refreshPositions(),a._trigger("activate",
d,f))})},stop:function(d,a){var c=b(this).data("draggable"),e=b.extend({},a,{item:c.element});b.each(c.sortables,function(){this.instance.isOver?(this.instance.isOver=0,c.cancelHelperRemoval=!0,this.instance.cancelHelperRemoval=!1,this.shouldRevert&&(this.instance.options.revert=!0),this.instance._mouseStop(d),this.instance.options.helper=this.instance.options._helper,"original"==c.options.helper&&this.instance.currentItem.css({top:"auto",left:"auto"})):(this.instance.cancelHelperRemoval=!1,this.instance._trigger("deactivate",
d,e))})},drag:function(d,a){var c=b(this).data("draggable"),e=this;b.each(c.sortables,function(){this.instance.positionAbs=c.positionAbs;this.instance.helperProportions=c.helperProportions;this.instance.offset.click=c.offset.click;this.instance._intersectsWith(this.instance.containerCache)?(this.instance.isOver||(this.instance.isOver=1,this.instance.currentItem=b(e).clone().removeAttr("id").appendTo(this.instance.element).data("sortable-item",!0),this.instance.options._helper=this.instance.options.helper,
this.instance.options.helper=function(){return a.helper[0]},d.target=this.instance.currentItem[0],this.instance._mouseCapture(d,!0),this.instance._mouseStart(d,!0,!0),this.instance.offset.click.top=c.offset.click.top,this.instance.offset.click.left=c.offset.click.left,this.instance.offset.parent.left-=c.offset.parent.left-this.instance.offset.parent.left,this.instance.offset.parent.top-=c.offset.parent.top-this.instance.offset.parent.top,c._trigger("toSortable",d),c.dropped=this.instance.element,
c.currentItem=c.element,this.instance.fromOutside=c),this.instance.currentItem&&this.instance._mouseDrag(d)):this.instance.isOver&&(this.instance.isOver=0,this.instance.cancelHelperRemoval=!0,this.instance.options.revert=!1,this.instance._trigger("out",d,this.instance._uiHash(this.instance)),this.instance._mouseStop(d,!0),this.instance.options.helper=this.instance.options._helper,this.instance.currentItem.remove(),this.instance.placeholder&&this.instance.placeholder.remove(),c._trigger("fromSortable",
d),c.dropped=!1)})}});b.ui.plugin.add("draggable","cursor",{start:function(){var d=b("body"),a=b(this).data("draggable").options;d.css("cursor")&&(a._cursor=d.css("cursor"));d.css("cursor",a.cursor)},stop:function(){var d=b(this).data("draggable").options;d._cursor&&b("body").css("cursor",d._cursor)}});b.ui.plugin.add("draggable","opacity",{start:function(d,a){var c=b(a.helper),e=b(this).data("draggable").options;c.css("opacity")&&(e._opacity=c.css("opacity"));c.css("opacity",e.opacity)},stop:function(d,
a){var c=b(this).data("draggable").options;c._opacity&&b(a.helper).css("opacity",c._opacity)}});b.ui.plugin.add("draggable","scroll",{start:function(){var d=b(this).data("draggable");d.scrollParent[0]!=document&&"HTML"!=d.scrollParent[0].tagName&&(d.overflowOffset=d.scrollParent.offset())},drag:function(d){var a=b(this).data("draggable"),c=a.options,e=!1;if(a.scrollParent[0]!=document&&"HTML"!=a.scrollParent[0].tagName){if(!c.axis||"x"!=c.axis)a.overflowOffset.top+a.scrollParent[0].offsetHeight-d.pageY<
c.scrollSensitivity?a.scrollParent[0].scrollTop=e=a.scrollParent[0].scrollTop+c.scrollSpeed:d.pageY-a.overflowOffset.top<c.scrollSensitivity&&(a.scrollParent[0].scrollTop=e=a.scrollParent[0].scrollTop-c.scrollSpeed);if(!c.axis||"y"!=c.axis)a.overflowOffset.left+a.scrollParent[0].offsetWidth-d.pageX<c.scrollSensitivity?a.scrollParent[0].scrollLeft=e=a.scrollParent[0].scrollLeft+c.scrollSpeed:d.pageX-a.overflowOffset.left<c.scrollSensitivity&&(a.scrollParent[0].scrollLeft=e=a.scrollParent[0].scrollLeft-
c.scrollSpeed)}else{if(!c.axis||"x"!=c.axis)d.pageY-b(document).scrollTop()<c.scrollSensitivity?e=b(document).scrollTop(b(document).scrollTop()-c.scrollSpeed):b(window).height()-(d.pageY-b(document).scrollTop())<c.scrollSensitivity&&(e=b(document).scrollTop(b(document).scrollTop()+c.scrollSpeed));if(!c.axis||"y"!=c.axis)d.pageX-b(document).scrollLeft()<c.scrollSensitivity?e=b(document).scrollLeft(b(document).scrollLeft()-c.scrollSpeed):b(window).width()-(d.pageX-b(document).scrollLeft())<c.scrollSensitivity&&
(e=b(document).scrollLeft(b(document).scrollLeft()+c.scrollSpeed))}!1!==e&&(b.ui.ddmanager&&!c.dropBehaviour)&&b.ui.ddmanager.prepareOffsets(a,d)}});b.ui.plugin.add("draggable","snap",{start:function(){var d=b(this).data("draggable"),a=d.options;d.snapElements=[];b(a.snap.constructor!=String?a.snap.items||":data(draggable)":a.snap).each(function(){var a=b(this),e=a.offset();this!=d.element[0]&&d.snapElements.push({item:this,width:a.outerWidth(),height:a.outerHeight(),top:e.top,left:e.left})})},drag:function(d,
a){for(var c=b(this).data("draggable"),e=c.options,f=e.snapTolerance,g=a.offset.left,k=g+c.helperProportions.width,i=a.offset.top,l=i+c.helperProportions.height,h=c.snapElements.length-1;0<=h;h--){var j=c.snapElements[h].left,m=j+c.snapElements[h].width,r=c.snapElements[h].top,p=r+c.snapElements[h].height;if(j-f<g&&g<m+f&&r-f<i&&i<p+f||j-f<g&&g<m+f&&r-f<l&&l<p+f||j-f<k&&k<m+f&&r-f<i&&i<p+f||j-f<k&&k<m+f&&r-f<l&&l<p+f){if("inner"!=e.snapMode){var q=Math.abs(r-l)<=f,u=Math.abs(p-i)<=f,s=Math.abs(j-
k)<=f,v=Math.abs(m-g)<=f;q&&(a.position.top=c._convertPositionTo("relative",{top:r-c.helperProportions.height,left:0}).top-c.margins.top);u&&(a.position.top=c._convertPositionTo("relative",{top:p,left:0}).top-c.margins.top);s&&(a.position.left=c._convertPositionTo("relative",{top:0,left:j-c.helperProportions.width}).left-c.margins.left);v&&(a.position.left=c._convertPositionTo("relative",{top:0,left:m}).left-c.margins.left)}var A=q||u||s||v;"outer"!=e.snapMode&&(q=Math.abs(r-i)<=f,u=Math.abs(p-l)<=
f,s=Math.abs(j-g)<=f,v=Math.abs(m-k)<=f,q&&(a.position.top=c._convertPositionTo("relative",{top:r,left:0}).top-c.margins.top),u&&(a.position.top=c._convertPositionTo("relative",{top:p-c.helperProportions.height,left:0}).top-c.margins.top),s&&(a.position.left=c._convertPositionTo("relative",{top:0,left:j}).left-c.margins.left),v&&(a.position.left=c._convertPositionTo("relative",{top:0,left:m-c.helperProportions.width}).left-c.margins.left));!c.snapElements[h].snapping&&(q||u||s||v||A)&&c.options.snap.snap&&
c.options.snap.snap.call(c.element,d,b.extend(c._uiHash(),{snapItem:c.snapElements[h].item}));c.snapElements[h].snapping=q||u||s||v||A}else c.snapElements[h].snapping&&c.options.snap.release&&c.options.snap.release.call(c.element,d,b.extend(c._uiHash(),{snapItem:c.snapElements[h].item})),c.snapElements[h].snapping=!1}}});b.ui.plugin.add("draggable","stack",{start:function(){var d=b(this).data("draggable").options,d=b.makeArray(b(d.stack)).sort(function(a,d){return(parseInt(b(a).css("zIndex"),10)||
0)-(parseInt(b(d).css("zIndex"),10)||0)});if(d.length){var a=parseInt(d[0].style.zIndex)||0;b(d).each(function(b){this.style.zIndex=a+b});this[0].style.zIndex=a+d.length}}});b.ui.plugin.add("draggable","zIndex",{start:function(d,a){var c=b(a.helper),e=b(this).data("draggable").options;c.css("zIndex")&&(e._zIndex=c.css("zIndex"));c.css("zIndex",e.zIndex)},stop:function(d,a){var c=b(this).data("draggable").options;c._zIndex&&b(a.helper).css("zIndex",c._zIndex);window.hi="hi"}})})(mQuery);